import type { Metadata } from "next";
import Link from "next/link";
import { UserRound } from "lucide-react";
import { siteConfig } from "@/lib/site-config";
import { buildMetadata } from "@/lib/metadata";
import { breadcrumbJsonLd } from "@/lib/jsonld";
import { JsonLd } from "@/components/json-ld";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { SectionHeading } from "@/components/section-heading";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = buildMetadata({
  title: "About",
  description:
    "What IntentNorth means, why understanding audience intent comes before optimization, and why manual analysis provides context automated scores miss.",
  path: "/about",
});

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <JsonLd
        id="about-breadcrumb-jsonld"
        data={breadcrumbJsonLd([
          { name: "Home", path: "/" },
          { name: "About", path: "/about" },
        ])}
      />

      <Breadcrumbs items={[{ name: "Home", path: "/" }, { name: "About", path: "/about" }]} />

      <div className="mt-6">
        <SectionHeading as="h1" eyebrow="About" title="Direction over more activity" />
      </div>

      <div className="prose-content mt-10 space-y-12">
        <section>
          <h2 className="text-xl font-semibold text-ink">What IntentNorth means</h2>
          <p className="mt-3 leading-relaxed text-slate">
            &ldquo;Intent&rdquo; represents what your audience is searching for, what they need, and what motivates
            them to act. &ldquo;North&rdquo; represents direction — clarity, and a guiding point to move toward. Put
            together, IntentNorth
            Solutions exists to identify what your audience actually wants and turn that understanding into a clear,
            prioritized direction for your business.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-ink">Our approach</h2>
          <p className="mt-3 leading-relaxed text-slate">
            Every engagement follows the same manual, evidence-based process: understand the business first, review
            the relevant material directly, separate urgent issues from strategic ones, document a clear plan, and
            define what to measure afterward. Nothing about that process is automated — see the full{" "}
            <Link href="/process" className="text-indigo underline underline-offset-2 hover:no-underline">
              five-stage process
            </Link>{" "}
            for details.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-ink">Why intent comes before optimization</h2>
          <p className="mt-3 leading-relaxed text-slate">
            It&apos;s possible to optimize a page, a profile, or a listing perfectly and still miss the mark, if the
            underlying assumption about what the audience wants is wrong. Optimization decisions made without a
            grounded understanding of intent tend to reflect internal assumptions rather than external reality.
            That&apos;s why every service, from SEO to positioning, starts with understanding intent before
            recommending changes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-ink">Why recommendations are prioritized</h2>
          <p className="mt-3 leading-relaxed text-slate">
            A long list of unranked findings isn&apos;t a plan — it&apos;s a source of paralysis. Every audit groups
            recommendations into immediate wins, high-impact improvements, and strategic investments, so effort goes
            where it&apos;s likely to matter most first.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-ink">Why manual analysis, not automated scores</h2>
          <p className="mt-3 leading-relaxed text-slate">
            Automated tools are good at surfacing data points, but they can&apos;t weigh context: what your business
            actually needs, which issues are cosmetic versus structural, or how a specific audience is likely to
            respond. A manual review can hold that context in mind throughout — which is why every audit, review, and
            plan at IntentNorth Solutions is performed directly by a person, not generated by a tool.
          </p>
        </section>
      </div>

      <section className="mt-16 rounded-2xl border border-mist bg-white p-8 sm:p-10">
        <div className="flex flex-col items-center gap-6 text-center sm:flex-row sm:text-left">
          <div
            aria-label="Founder photo placeholder"
            role="img"
            className="flex h-28 w-28 shrink-0 items-center justify-center rounded-full border border-dashed border-mist bg-cloud"
          >
            <UserRound aria-hidden="true" className="h-12 w-12 text-slate" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-ink">{siteConfig.founder.name}</h2>
            <p className="mt-1 text-xs font-medium uppercase tracking-wide text-slate">Founder — photo and biography placeholder</p>
            <p className="mt-3 text-sm leading-relaxed text-slate">{siteConfig.founder.bioPlaceholder}</p>
          </div>
        </div>
      </section>

      <div className="mt-16 text-center">
        <Button asChild size="lg">
          <Link href="/request-audit">Request an audit</Link>
        </Button>
      </div>
    </div>
  );
}
